import { IDataBaseTraceabilityData, IBarChart, IMixedChart, IPieChart,
    ITableDataFactoryMain,
    ITableDataFactoryInfo,
    ITableProjectPriorityDifficulty,
    IPriorityDifficulty,
    ITableDataUiDesignedWithData,
    //ITableDataFonctionAlarmByAreas, ITableDataFonctionNotLinkedByAreas, ITableDataFonctionNeverDoneByAreas, ITableDataFonctionToCheckByAreas
} from './types'

import requestSql from "@/utils/requestSql";
import i18n from "@/i18n";

export interface AITraceabilityQuery {
    idFactory: string | undefined
}
export const defaultTraceabilityQuery: AITraceabilityQuery = {
    idFactory: undefined,
}
export const defaultTraceabilityData: IDataBaseTraceabilityData = {
    firstAnnualLosses: 0,
    firstAnnualPrice: 0,
    currentAnnualLosses: 0,
    currentAnnualPrice: 0,
    areas: []
}

export const defaultPriorityDifficulty: IPriorityDifficulty = {
    veryHigh: {
        veryHard: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        hard: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        difficile: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        normal: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        easy: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
    },
    high: {
        veryHard: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        hard: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        difficile: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        normal: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        easy: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
    },
    normal: {
        veryHard: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        hard: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        difficile: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        normal: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        easy: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
    },
    low: {
        veryHard: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        hard: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        difficile: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        normal: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        easy: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
    },
    veryLow: {
        veryHard: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        hard: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        difficile: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        normal: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
        easy: {
            number: 0,
            projectFunctionLinkedFirstAnnualLosses: 0,
            projectFunctionLinkedFirstAnnualPrice: 0,
            projectFunctionLinkedCurrentAnnualLosses: 0,
            projectFunctionLinkedCurrentAnnualPrice: 0,
            projectFunctionLinkedRecoveryAnnualLosses: 0,
            projectFunctionLinkedRecoveryAnnualPrice: 0,
        },
    },
}

export const getDBTraceabilitys = (params: any) =>
    requestSql({
        headers: { },
        url: '/Traceabilitys/all',
        method: 'get',
        params
    })
