/** Declaration file generated by dts-gen */

export = js_cookie;

declare function js_cookie(): void;

declare namespace js_cookie {
    const defaults: {
    };

    function get(key: any): any;

    function getJSON(key: any): any;

    function remove(key: any, attributes: any): void;

    function set(key: any, value: any, attributes: any): any;

    function withConverter(converter: any): any;

}

